void    nd_devs_init();
uae_u32 nd_io_lget(uaecptr addr);
uae_u32 nd_io_wget(uaecptr addr);
uae_u32 nd_io_bget(uaecptr addr);
void    nd_io_lput(uaecptr addr, uae_u32 l);
void    nd_io_wput(uaecptr addr, uae_u32 w);
void    nd_io_bput(uaecptr addr, uae_u32 b);
uae_u32 nd_ramdac_bget(uaecptr addr);
void    nd_ramdac_bput(uaecptr addr, uae_u32 b);
uae_u32 nd_dp_lget(uaecptr addr);
void    nd_dp_lput(uaecptr addr, uae_u32 b);
